openapi: 3.0.0
info:
  title: "Flask REST API"
  description: "Something to aid in job security"
  version: "1.0.0"

servers:
  - url: "/api"
paths:
  /results:
    get:
      operationId: "results.read_all"
      tags:
        - "People"
      summary: "Read the list of people"
      responses:
        "200":
          description: "Successfully read people list"